// <auto-generated />
namespace comment_system_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Upvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upvote));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081137476_Upvote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
