// <auto-generated />
namespace comment_system_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_Comments_Prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_Comments_Prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201810072128359_Update_Comments_Prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
